#!/bin/bash
red='\033[1;31m'
nc='\033[0m'
PKGS=(chromium vlc audacity blender gimp krita inkscape gnome-tweak-tool dconf-editor shotwell obs-studio cmatrix firefox mpv apache cups hplip wine winetricks lib32-nvidia-utils zsh zsh-completions gparted jre-openjdk openssh gnome-software-packagekit-plugin thunderbird aisleriot marker virtualbox)
printf "\n\n${red}--- Installing packages ---\n\n${nc}"

for PKG in "${PKGS[@]}"; do
pacman -S --noconfirm --needed $PKG
done
echo -e "[Desktop Entry]\nHidden=true" > /tmp/1
find /usr -name "*lsp_plug*desktop" 2>/dev/null | cut -f 5 -d '/' | xargs -I {} cp /tmp/1 ~/.local/share/applications/{}
printf "\n\n${red}--- Enable services ---\n\n${nc}"

systemctl enable sshd
systemctl enable httpd
systemctl enable org.cups.cupsd

printf "\n\n${red}--- Download pikaur and yaru ---\n\n${nc}"

git clone https://aur.archlinux.org/pikaur.git
git clone https://aur.archlinux.org/yaru.git
chmod -R 777 yaru
chmod -R 777 pikaur

printf "\n\n${red}--- Done. ---\n\n${nc}"
