#!/bin/bash
red='\033[1;31m'
nc='\033[0m'
PKGS_Aur=(wps-office preload spotify timeshift timeshift-autosnap gnome-shell-extension-dash-to-dock-git gnome-shell-extension-desktop-icons-ng whatsapp-nativefier-dark ttf-ms-fonts all-repository-fonts visual-studio-code-bin)
printf "\n${red}--- Installing packages from the AUR  ---\n\n${nc}"
cd ./pikaur
makepkg -si --noconfirm
pikaur -S --noconfirm yaru-icon-theme
cd ..
cd ..
cd ..
cd ./yaru
makepkg -si --noconfirm
for PKG in "${PKGS_Aur[@]}"; do
pikaur -S --noconfirm $PKG
done
printf "\n${red}--- Done  ---\n\n${nc}"

